language: python

env:
  - TOXENV=py27
  - TOXENV=py34

matrix:
  include:
  - python: 3.5
    env: TOXENV=py35
  - python: 3.5
    env: TOXENV=lint

before_script:
  - pip install tox

script:
  - tox
